#+TITLE: Alpine Nikola Dockerfile

This dockerfile builds a custom Nikola build environment based on a base
[[https://hub.docker.com/_/alpine][alpine image]].

 - Strongly based on [[https://gitlab.com/paddy-hack/nikola][paddy-hack]] and [[https://github.com/abellmann/nikola-orgmode][abellmann]] files

 - Allows using [[https://orgmode.org/][orgmode]] as markdown language

 - Used [[https://gitlab.com/csantosb-blogs/blog-tech][here]] along with [[https://docs.gitlab.com/ee/ci/][gitlbab-ci]]

Get it from [[https://hub.docker.com/r/csantosb/alpine-nikola][docker hub]].

* License

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the [[http://www.gnu.org/licenses/gpl.txt][GNU General Public License]]
along with this program. If not, see http://www.gnu.org/licenses/gpl.html.
