#+TITLE: Archlinux VHDL Dockerfile

This dockerfile builds a custom VHDL testing environment based on a base
[[https://hub.docker.com/_/archlinux/][archlinux image]].

 - It includes latest [[https://aur.archlinux.org/packages/ghdl-gcc-git/][ghdl-gcc-git]] and [[https://aur.archlinux.org/packages/python-cocotb-git/][python-cocotb-git]] packages, including pre
   compiled Vivado 2019.2 libraries

 - It includes a (sudo powered) notroot user to work as once the image is
   created. This is first, necessary to to install from the [[https://aur.archlinux.org/][AUR]], and secondly
   useful when needing to install aditional ancillary packages within the
   container

Get it from [[https://hub.docker.com/r/csantosb/arch-vhdl][docker hub]].

* License

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the [[http://www.gnu.org/licenses/gpl.txt][GNU General Public License]]
along with this program. If not, see http://www.gnu.org/licenses/gpl.html.
