#+TITLE: Archlinux testing Dockerfile

This dockerfile builds a custom package build environment based on a base
[[https://hub.docker.com/_/archlinux/][archlinux image]].

 - It adds latest [[https://aur.archlinux.org/packages/yay-bin/][yay-bin]] package and gcc, git, make, binutils, sudo, diffutils
   and fakeroot packages

 - Includes also a (sudo powered) notroot user to work as once the image is
   created, which is necessary to install packages from the [[https://aur.archlinux.org/][AUR]]. Sudo access
   might be useful in case of needing to install aditional ancillary packages
   within the container

 - Used for testing [[https://gitlab.com/aur-packages][these]] aur packages

Get it from [[https://hub.docker.com/r/csantosb/arch-testing][docker hub]].

* License

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the [[http://www.gnu.org/licenses/gpl.txt][GNU General Public License]]
along with this program. If not, see http://www.gnu.org/licenses/gpl.html.
